#!/usr/bin/env python3
"""Regenerate the Ukraine map used by the Geography section.

The previous map was one silhouette path and two hand-drawn quadratic curves.
Two of the four places named beside it had no line at all, the Kyiv curve's
control point sat outside both of its endpoints so the route bowed backwards,
and the Odesa label ran straight into the coastline.

This produces, offline and once:

  * 27 oblast paths (24 oblasts, Kyiv city, Sevastopol, Crimea) plus a heavier
    national outline drawn over them, so the country reads as a country and the
    home oblast can be highlighted;
  * four routes from the elevator to Kyiv, the port of Odesa, Vinnytsia and
    Haisyn, every one of them a cubic arc generated by the same rule rather
    than eyeballed;
  * label anchors pushed away from the country's centroid, with the side each
    label opens towards, so no label can sit on top of the geometry it
    describes.

The output is committed as templates/ukraine-map.svg.j2. Nothing here runs in
the browser and the site keeps making zero third-party requests.

    python3 tools/build_map.py            # uses the cached GeoJSON if present
    python3 tools/build_map.py --refresh  # re-download from Natural Earth
"""
from __future__ import annotations

import argparse
import json
import math
import os
import sys
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CACHE = os.path.join(ROOT, "tools", ".cache", "ne_10m_admin_1_ua.json")
SOURCE = (
    "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/"
    "master/geojson/ne_10m_admin_1_states_provinces.geojson"
)

# The viewBox is proportioned to Ukraine itself (about 1.5:1 once the mid-
# latitude correction is applied) instead of the old 760x460, which was wider
# than the country and left it floating in the middle of the card. The padding
# is the room the labels need to sit outside the border without being clipped.
VIEW_W, VIEW_H = 760.0, 512.0
PAD = 40.0
SIMPLIFY_DEG = 0.045         # borders need more detail than the old 0.035 outline
MIN_RING = 6.0               # viewBox units: drop offshore specks nobody can see

# Plotted points, from docs/map-source.md.
PLACES = {
    "home":      (49.0716, 29.3608),   # CENTRAGRO PLUS demo location
    "vinnytsia": (49.2331, 28.4682),
    "haisyn":    (48.8114, 29.3891),
    "odesa":     (46.4825, 30.7233),
    "kyiv":      (50.4501, 30.5234),
}
HOME_OBLAST = "Vinnytsya"


# --------------------------------------------------------------------------
# geometry
# --------------------------------------------------------------------------

def fetch(refresh: bool) -> dict:
    if os.path.exists(CACHE) and not refresh:
        with open(CACHE, encoding="utf-8") as fh:
            return json.load(fh)
    os.makedirs(os.path.dirname(CACHE), exist_ok=True)
    sys.stderr.write("downloading Natural Earth admin-1 …\n")
    with urllib.request.urlopen(SOURCE, timeout=180) as resp:
        data = json.load(resp)
    feats = [f for f in data["features"]
             if (f["properties"].get("iso_a2") or "").upper() == "UA"]
    # Natural Earth's default point of view files Crimea and Sevastopol under
    # Russia. Ukraine's internationally recognised borders include both, and the
    # map this replaces drew them as Ukrainian — so they are pulled back in by
    # name. This is a deliberate editorial decision, not a data cleanup, and it
    # is recorded in docs/map-source.md.
    claimed = {"Crimea", "Sevastopol"}
    feats += [f for f in data["features"]
              if f["properties"].get("name") in claimed]
    out = {"type": "FeatureCollection", "features": feats}
    with open(CACHE, "w", encoding="utf-8") as fh:
        json.dump(out, fh)
    return out


def rings_of(geom: dict):
    """Every outer ring in a Polygon or MultiPolygon, largest first."""
    if geom["type"] == "Polygon":
        polys = [geom["coordinates"]]
    elif geom["type"] == "MultiPolygon":
        polys = geom["coordinates"]
    else:
        return []
    return [p[0] for p in polys]


def simplify(points, tol):
    """Douglas-Peucker. Keeps borders honest while shedding coastline noise."""
    if len(points) < 3:
        return points
    a, b = points[0], points[-1]
    dx, dy = b[0] - a[0], b[1] - a[1]
    span = math.hypot(dx, dy)
    worst, idx = -1.0, 0
    for i in range(1, len(points) - 1):
        px, py = points[i]
        if span == 0:
            d = math.hypot(px - a[0], py - a[1])
        else:
            d = abs(dy * px - dx * py + b[0] * a[1] - b[1] * a[0]) / span
        if d > worst:
            worst, idx = d, i
    if worst <= tol:
        return [a, b]
    return simplify(points[:idx + 1], tol)[:-1] + simplify(points[idx:], tol)


def make_projection(features):
    """Equirectangular, scaled to fit the viewBox with the latitude correction
    applied at the country's mid-latitude so Ukraine is not visibly squashed."""
    lons, lats = [], []
    for f in features:
        for ring in rings_of(f["geometry"]):
            for lon, lat in ring:
                lons.append(lon)
                lats.append(lat)
    lon0, lon1 = min(lons), max(lons)
    lat0, lat1 = min(lats), max(lats)
    k = math.cos(math.radians((lat0 + lat1) / 2))

    w = (lon1 - lon0) * k
    h = lat1 - lat0
    scale = min((VIEW_W - 2 * PAD) / w, (VIEW_H - 2 * PAD) / h)
    ox = (VIEW_W - w * scale) / 2
    oy = (VIEW_H - h * scale) / 2

    def project(lon, lat):
        # Whole units. The map paints about 1.5 device pixels per unit, so a
        # decimal place buys nothing visible and costs a quarter of the file.
        x = ox + (lon - lon0) * k * scale
        y = oy + (lat1 - lat) * scale
        return int(round(x)), int(round(y))

    return project


def path_for(geom, project, tol):
    out = []
    for ring in rings_of(geom):
        pts = [project(lon, lat) for lon, lat in ring]
        # drop consecutive duplicates the projection's rounding creates
        dedup = [pts[0]]
        for p in pts[1:]:
            if p != dedup[-1]:
                dedup.append(p)
        pts = simplify(dedup, tol)
        if len(pts) < 4:
            continue
        xs = [x for x, _ in pts]
        ys = [y for _, y in pts]
        if max(xs) - min(xs) < MIN_RING and max(ys) - min(ys) < MIN_RING:
            continue
        out.append("M" + "L".join(f"{x} {y}" for x, y in pts) + "Z")
    return "".join(out)


def arc(p0, p1, lift=0.18):
    """Cubic arc bowing to one consistent side of the straight line.

    One rule for all four routes: control points sit a third and two thirds
    along the chord, offset perpendicular by a share of its length. Short hops
    therefore lift a little and long hauls lift a lot, and because the offset
    keeps its sign every route curves the same way — a fan rather than a
    tangle. The old map bent one route with a control point that lay outside
    both of its ends, which is why it doubled back on itself.
    """
    (x0, y0), (x1, y1) = p0, p1
    dx, dy = x1 - x0, y1 - y0
    length = math.hypot(dx, dy) or 1.0
    nx, ny = -dy / length, dx / length
    off = length * lift
    c1 = (x0 + dx / 3 + nx * off, y0 + dy / 3 + ny * off)
    c2 = (x0 + dx * 2 / 3 + nx * off, y0 + dy * 2 / 3 + ny * off)
    return (f"M{x0:.1f},{y0:.1f}C{c1[0]:.1f},{c1[1]:.1f} "
            f"{c2[0]:.1f},{c2[1]:.1f} {x1:.1f},{y1:.1f}")


# --------------------------------------------------------------------------
# emit
# --------------------------------------------------------------------------

TEMPLATE_HEAD = """<svg class="ukraine-map" viewBox="0 0 760 512" role="img" aria-labelledby="uk-map-title uk-map-desc">
<title id="uk-map-title">{{ c.geo.title }}</title>
<desc id="uk-map-desc">{{ c.geo.lead }}</desc>
<defs>
<linearGradient id="map-fill" x1="0" y1="0" x2="1" y2="1"><stop stop-color="var(--map-hi)"/><stop offset="1" stop-color="var(--map-lo)"/></linearGradient>
<filter id="route-glow" x="-40%" y="-40%" width="180%" height="180%"><feGaussianBlur stdDeviation="3" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter>
</defs>
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--refresh", action="store_true")
    args = ap.parse_args()

    data = fetch(args.refresh)
    feats = data["features"]
    if not feats:
        raise SystemExit("no Ukrainian admin-1 features found")
    project = make_projection(feats)

    # oblasts, largest first so small ones are painted on top and stay clickable
    oblasts = []
    for f in feats:
        pr = f["properties"]
        name = pr.get("name") or pr.get("name_local") or ""
        gn = pr.get("gn_name") or name
        d = path_for(f["geometry"], project, SIMPLIFY_DEG)
        if not d:
            continue
        home = HOME_OBLAST.lower() in (name or "").lower()
        oblasts.append((name, gn, d, home))

    pts = {k: project(lon, lat) for k, (lat, lon) in PLACES.items()}
    home = pts["home"]

    routes = [
        ("kyiv", "north", arc(home, pts["kyiv"], 0.15)),
        ("odesa", "port", arc(home, pts["odesa"], 0.15)),
        ("vinnytsia", "regional", arc(home, pts["vinnytsia"], 0.26)),
        ("haisyn", "local", arc(home, pts["haisyn"], 0.34)),
    ]

    # Labels open away from the map's middle, so none of them lies across the
    # country. Order matches content/*.json geo.distances.
    labels = [
        ("vinnytsia", pts["vinnytsia"], -14, -12, "end"),
        ("haisyn", pts["haisyn"], 16, 26, "start"),
        ("odesa", pts["odesa"], -16, 30, "end"),
        ("kyiv", pts["kyiv"], 18, -10, "start"),
    ]

    out = [TEMPLATE_HEAD]
    out.append('<g class="ukraine-map__oblasts">\n')
    for name, gn, d, is_home in oblasts:
        cls = "ukraine-map__oblast" + (" is-home" if is_home else "")
        out.append(f'<path class="{cls}" d="{d}"><title>{gn}</title></path>\n')
    out.append("</g>\n")

    for key, kind, d in routes:
        out.append(f'<path class="ukraine-map__route ukraine-map__route--{kind}" '
                   f'data-place="{key}" pathLength="1" d="{d}"/>\n')

    for i, (key, (x, y), dx, dy, anchor) in enumerate(labels):
        out.append(
            f'<g class="ukraine-map__point ukraine-map__point--{key}" data-place="{key}" transform="translate({x} {y})">'
            f'<circle class="ukraine-map__pulse" r="9"/><circle r="4"/>'
            f'<text x="{dx}" y="{dy}" text-anchor="{anchor}">{{{{ c.geo.distances[{i}].to }}}}</text>'
            f'<text class="ukraine-map__km" x="{dx}" y="{dy + 17}" text-anchor="{anchor}">'
            f'{{{{ c.geo.distances[{i}].km }}}}</text></g>\n')

    out.append(f'<g class="ukraine-map__hub" transform="translate({home[0]} {home[1]})" '
               f'aria-label="{{{{ c.brand.word_1 }}}}">'
               f'<circle class="ukraine-map__pulse ukraine-map__pulse--hub" r="18"/>'
               f'<circle r="13"/></g>\n')
    out.append("</svg>\n")

    dest = os.path.join(ROOT, "templates", "ukraine-map.svg.j2")
    with open(dest, "w", encoding="utf-8") as fh:
        fh.write("".join(out))

    print(f"oblasts: {len(oblasts)}  routes: {len(routes)}  "
          f"bytes: {os.path.getsize(dest):,}")
    print("home oblast highlighted:",
          any(h for _, _, _, h in oblasts) or "NOT FOUND")
    return 0


if __name__ == "__main__":
    sys.exit(main())
