#!/usr/bin/env python3
"""Build the static site: two locales from one template, one minified CSS/JS bundle.

Everything the browser downloads is produced here and committed, so GitHub Pages
can serve the repository directly with no CI step and no build on the server.

  python3 tools/build_site.py

Outputs: index.html, en/index.html, 404.html, assets/css/main.css,
assets/js/app.js, assets/img/og-*.jpg, robots.txt, sitemap.xml,
site.webmanifest, .nojekyll
"""
import datetime
import json
import os
import re
import shutil
import sys

import rcssmin
import rjsmin
from jinja2 import Environment, FileSystemLoader, StrictUndefined
from markupsafe import Markup

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE = "https://xxxquide.github.io/Agro-Site/"
SUBPATH = "/Agro-Site/"          # absolute prefix, needed by 404.html only
BUILD_YEAR = 2026

CSS_PARTS = [
    "assets/css/fonts.css",       # generated by tools/build_fonts.py
    "src/css/01-tokens.css",
    "src/css/02-base.css",
    "src/css/03-components.css",
    "src/css/04-sections.css",
    "src/css/05-motion.css",
    "src/css/06-responsive.css",
]

LOCALES = [("uk", "index.html"), ("en", "en/index.html")]

# which cluster photo backs each parcel in the geography plan
GEO_IMGS = ["ops-elevator", "crop-wheat", "crop-corn"]

# orbit arms: irregular angles so the four pills never line up
ORBIT = [
    {"a": 22, "r": "30%", "d": 54},
    {"a": 112, "r": "37%", "d": 64},
    {"a": 203, "r": "31%", "d": 48},
    {"a": 292, "r": "38%", "d": 59},
]


def rel(*parts):
    return os.path.join(ROOT, *parts)


def read(path):
    with open(rel(path), encoding="utf-8") as fh:
        return fh.read()


def write(path, text):
    full = rel(path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w", encoding="utf-8") as fh:
        fh.write(text)
    return len(text.encode("utf-8"))


# ---------------------------------------------------------------------------
# assets: one CSS file, one JS file
# ---------------------------------------------------------------------------

def build_css():
    raw = "\n".join(read(p) for p in CSS_PARTS)
    mini = rcssmin.cssmin(raw)
    n = write("assets/css/main.css", mini)
    return len(raw.encode()), n


def build_js():
    raw = read("src/js/app.js")
    mini = rjsmin.jsmin(raw)
    n = write("assets/js/app.js", mini)
    return len(raw.encode()), n


# ---------------------------------------------------------------------------
# template helpers
# ---------------------------------------------------------------------------

def load_manifest():
    with open(rel("assets/img/manifest.json"), encoding="utf-8") as fh:
        return json.load(fh)


def make_srcset(imgs):
    def srcset(name, ext):
        m = imgs[name]
        return ", ".join(
            f"{{P}}assets/img/{name}-{w}.{ext} {w}w" for w in m["widths"]
        )
    return srcset


def fan_transforms(n):
    """Per-card 3D placement for the hero fan.

    Computed here rather than in CSS so the arc stays exact for any card count
    and the stylesheet needs no abs()/trig support.
    """
    mid = (n - 1) / 2
    out = []
    for i in range(n):
        a = i - mid
        d = abs(a)
        out.append({
            "ry": round(-a * 8.5, 2),
            "rz": round(a * 1.35, 2),
            "ty": round(d * d * 4.2 + d * 5.0, 1),
            "tz": round(-d * 26, 1),
            "sc": round(1 - d * 0.019, 3),
            "z": n - int(d * 2),
        })
    return out


def chart_builder(imgs):
    """Return a callable the template uses for both chart sizes.

    Bars are scaled between the series minimum and maximum rather than from
    zero: with a 0-baseline a 4.9 -> 6.4 t/ha spread is visually flat. Every
    exact value is printed above its bar, so nothing is hidden by the choice.
    """
    def chart_html(series, big=False):
        vals = [s["v"] for s in series]
        lo, hi = min(vals), max(vals)
        span = (hi - lo) or 1
        cols, years = [], []
        for i, s in enumerate(series):
            pct = 42 + 58 * (s["v"] - lo) / span
            cls = "chart__col"
            if s["v"] == hi:
                cls += " chart__col--peak"
            elif s["v"] == lo:
                cls += " chart__col--dip"
            label = f'{s["v"]:.1f}'.replace(".", DECIMAL)
            cols.append(
                f'<div class="{cls}" style="--h:{pct:.1f}%;--i:{i}">'
                f'<span class="chart__val">{label}</span>'
                f'<span class="chart__fill"></span></div>'
            )
            years.append(f"<span>{s['year']}</span>")
        return Markup(
            '<div class="chart"><div class="chart__plot">'
            + "".join(cols)
            + '</div><div class="chart__years">'
            + "".join(years)
            + "</div></div>"
        )
    return chart_html


# ---------------------------------------------------------------------------
# structured data
# ---------------------------------------------------------------------------

def build_jsonld(c, lang, canonical):
    org_id = BASE + "#org"
    crops = c["crops"]["items"]

    org = {
        "@type": "Organization",
        "@id": org_id,
        "name": c["brand"]["name"],
        "legalName": c["brand"]["legal"],
        "url": BASE,
        "logo": {
            "@type": "ImageObject",
            "url": BASE + "assets/icons/logo-lockup.png",
            "width": 1120, "height": 280,
        },
        "image": BASE + f"assets/img/og-{lang}.jpg",
        "description": c["seo"]["description"],
        "foundingDate": "2008",
        "email": c["contact"]["email"],
        "telephone": c["contact"]["phone"],
        "address": {
            "@type": "PostalAddress",
            "streetAddress": "вул. Зарічна, 4" if lang == "uk" else "4 Zarichna St",
            "addressLocality": "Сорока" if lang == "uk" else "Soroka",
            "addressRegion": "Вінницька область" if lang == "uk" else "Vinnytsia region",
            "postalCode": "22731",
            "addressCountry": "UA",
        },
        "areaServed": {"@type": "Country", "name": "Ukraine"},
        "knowsLanguage": ["uk", "en"],
        "naics": "111140",
        "hasOfferCatalog": {
            "@type": "OfferCatalog",
            "name": c["crops"]["title"],
            "itemListElement": [
                {
                    "@type": "Offer",
                    "itemOffered": {
                        "@type": "Product",
                        "name": cr["name"],
                        "description": cr["text"],
                        "image": BASE + f'assets/img/{cr["img"]}-1120.webp',
                    },
                    "availability": "https://schema.org/InStock",
                    "eligibleQuantity": {
                        "@type": "QuantitativeValue",
                        "value": cr["volume"].split()[0].replace(" ", "").replace(",", ""),
                        "unitCode": "TNE",
                    },
                }
                for cr in crops
            ],
        },
    }

    place = {
        "@type": "LocalBusiness",
        "@id": BASE + "#place",
        "name": c["brand"]["name"],
        "parentOrganization": {"@id": org_id},
        "image": BASE + f"assets/img/og-{lang}.jpg",
        "address": org["address"],
        "geo": {"@type": "GeoCoordinates", "latitude": 49.0716, "longitude": 29.3608},
        "telephone": c["contact"]["phone"],
        "email": c["contact"]["email"],
        "url": canonical,
        "openingHoursSpecification": [{
            "@type": "OpeningHoursSpecification",
            "dayOfWeek": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
            "opens": "08:00", "closes": "18:00",
        }],
    }

    site = {
        "@type": "WebSite",
        "@id": BASE + "#site",
        "url": BASE,
        "name": c["brand"]["name"],
        "publisher": {"@id": org_id},
        "inLanguage": ["uk", "en"],
    }

    page = {
        "@type": "WebPage",
        "@id": canonical + "#page",
        "url": canonical,
        "name": c["seo"]["title"],
        "description": c["seo"]["description"],
        "isPartOf": {"@id": BASE + "#site"},
        "about": {"@id": org_id},
        "inLanguage": lang,
        "primaryImageOfPage": {
            "@type": "ImageObject",
            "url": BASE + "assets/img/hero-field-1920.webp",
        },
    }

    faq = {
        "@type": "FAQPage",
        "@id": canonical + "#faq",
        "isPartOf": {"@id": canonical + "#page"},
        "inLanguage": lang,
        "mainEntity": [
            {
                "@type": "Question",
                "name": q["q"],
                "acceptedAnswer": {"@type": "Answer", "text": q["a"]},
            }
            for q in c["faq"]["items"]
        ],
    }

    graph = {"@context": "https://schema.org", "@graph": [org, place, site, page, faq]}
    return json.dumps(graph, ensure_ascii=False, separators=(",", ":"))


# ---------------------------------------------------------------------------
# side files
# ---------------------------------------------------------------------------

def build_side_files(uk):
    write(".nojekyll", "")

    write("robots.txt", f"""User-agent: *
Allow: /

Sitemap: {BASE}sitemap.xml
""")

    today = f"{BUILD_YEAR}-08-05"
    urls = []
    for lang, out in LOCALES:
        loc = BASE if lang == "uk" else BASE + "en/"
        alts = "".join(
            f'\n    <xhtml:link rel="alternate" hreflang="{l}" '
            f'href="{BASE if l == "uk" else BASE + "en/"}"/>'
            for l in ("uk", "en")
        )
        alts += f'\n    <xhtml:link rel="alternate" hreflang="x-default" href="{BASE}en/"/>'
        urls.append(
            f"""  <url>
    <loc>{loc}</loc>
    <lastmod>{today}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>{"1.0" if lang == "uk" else "0.9"}</priority>{alts}
  </url>"""
        )

    write("sitemap.xml", f"""<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
{chr(10).join(urls)}
</urlset>
""")

    write("site.webmanifest", json.dumps({
        "name": uk["brand"]["legal"],
        "short_name": uk["brand"]["word_1"],
        "description": uk["seo"]["description"],
        "start_url": SUBPATH,
        "scope": SUBPATH,
        "display": "standalone",
        "background_color": "#F7F6F1",
        "theme_color": "#0E2A1B",
        "lang": "uk",
        "dir": "ltr",
        "icons": [
            {"src": SUBPATH + "assets/icons/favicon-32.png", "sizes": "32x32", "type": "image/png"},
            {"src": SUBPATH + "assets/icons/favicon-96.png", "sizes": "96x96", "type": "image/png"},
            {"src": SUBPATH + "assets/icons/apple-touch-icon.png", "sizes": "180x180", "type": "image/png"},
            {"src": SUBPATH + "assets/icons/favicon.svg", "sizes": "any", "type": "image/svg+xml"},
        ],
    }, ensure_ascii=False, indent=1))


def build_404(uk):
    return write("404.html", f"""<!DOCTYPE html>
<html lang="uk">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Сторінку не знайдено — {uk["brand"]["name"]}</title>
<meta name="robots" content="noindex, follow">
<link rel="icon" href="{SUBPATH}assets/icons/favicon.svg" type="image/svg+xml">
<link rel="stylesheet" href="{SUBPATH}assets/css/main.css">
<style>
.nf{{min-height:100svh;display:grid;place-items:center;text-align:center;padding:2rem}}
.nf__in{{display:flex;flex-direction:column;align-items:center;gap:1.25rem;max-width:34rem}}
.nf__code{{font-family:var(--mono);font-size:.72rem;font-weight:600;letter-spacing:.18em;color:var(--text-faint)}}
</style>
</head>
<body>
<main class="nf">
  <div class="nf__in">
    <svg width="56" height="56" viewBox="0 0 48 48" aria-hidden="true">{read("assets/icons/favicon.svg").split(">", 1)[1].rsplit("</svg>", 1)[0]}</svg>
    <p class="nf__code">404 — NOT FOUND</p>
    <h1>Такої сторінки немає</h1>
    <p class="lead">Можливо, посилання застаріло. Повернімося на головну — там усе про наші культури, потужності та умови співпраці.</p>
    <a class="btn" href="{SUBPATH}">На головну<span class="btn__badge"><svg viewBox="0 0 12 12" fill="none" aria-hidden="true"><path d="M2.5 9.5 9.5 2.5M9.5 2.5H4.2M9.5 2.5v5.3" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></svg></span></a>
  </div>
</main>
</body>
</html>
""")


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

DECIMAL = ","   # set per locale before each render


def main():
    global DECIMAL

    imgs = load_manifest()
    logo_mark = read("assets/icons/logo-mark.svg")
    logo_inner = logo_mark.split(">", 1)[1].rsplit("</svg>", 1)[0]

    env = Environment(
        loader=FileSystemLoader(rel("templates")),
        undefined=StrictUndefined,
        trim_blocks=False,
        lstrip_blocks=True,
        autoescape=True,
    )
    tpl = env.get_template("page.html.j2")

    css_raw, css_min = build_css()
    js_raw, js_min = build_js()

    srcset_fn = make_srcset(imgs)
    chart_html = chart_builder(imgs)
    sizes = {}

    for lang, out in LOCALES:
        with open(rel("content", f"{lang}.json"), encoding="utf-8") as fh:
            c = json.load(fh)

        DECIMAL = "," if lang == "uk" else "."
        prefix = c["dir_prefix"]
        canonical = BASE if lang == "uk" else BASE + "en/"
        thousands = " " if lang == "uk" else ","

        def fmt_num(n, _t=thousands):
            return f"{n:,}".replace(",", _t)

        def srcset(name, ext, _p=prefix):
            return srcset_fn(name, ext).replace("{P}", _p)

        html = tpl.render(
            c=c,
            imgs=imgs,
            base=BASE,
            canonical=canonical,
            year=BUILD_YEAR,
            logo_mark=Markup(logo_inner),
            srcset=srcset,
            chart_html=chart_html,
            fan=fan_transforms(len(c["hero"]["cards"])),
            orbit=ORBIT,
            geo_imgs=GEO_IMGS,
            fmt_num=fmt_num,
            ha="га" if lang == "uk" else "ha",
            tel="+" + re.sub(r"\D", "", c["contact"]["phone"]),
            jsonld=Markup(build_jsonld(c, lang, canonical)),
        )

        # collapse the blank lines Jinja's block tags leave behind
        html = re.sub(r"\n{3,}", "\n\n", html)
        sizes[out] = write(out, html)

    build_side_files(json.load(open(rel("content", "uk.json"), encoding="utf-8")))
    nf = build_404(json.load(open(rel("content", "uk.json"), encoding="utf-8")))

    print("BUILD OK")
    print(f"  css      {css_raw/1024:6.1f} KB -> {css_min/1024:6.1f} KB min")
    print(f"  js       {js_raw/1024:6.1f} KB -> {js_min/1024:6.1f} KB min")
    for out, n in sizes.items():
        print(f"  {out:16s} {n/1024:6.1f} KB")
    print(f"  404.html         {nf/1024:6.1f} KB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
